LAND_DIM_1 = 100               # land_dim_1
LAND_DIM_2 = 100               # land_dim_2
LAND_OWNERSHIP = TRUE                 # land_ownership
RES_BIRTH_TYPE = 2                   # res_birth_type
RES_DEATH_TYPE = 2                   # res_death_type
LAMBDA = 0.3                   # lambda
REMOVE_PR = 0                   # remove_pr
RES_BIRTH_K = 100000              # res_birth_K
RES_DEATH_K = 2000                # res_death_K
MANAGE_TARGET = 1000                 # manage_target
RESOURCE_INI = 1000              # RESOURCE_ini
STAKEHOLDERS = 8                     # stakeholders
RES_CONSUME = 0.5              # res_consume
AGENT_VIEW = 50               # agent_view
TIMES_OBSERVE = 10                # times_observe
SCARING = TRUE              # scaring
CULLING = TRUE               # culling
TEND_CROP = TRUE          # tend_cops
TEND_CROP_YLD = 0.5                 # tend_crop_yield              # 0.475
MINIMUM_COST = 10                   # minimum cost 
