test = gmse(time_max = 50,
            land_dim_1 = 100,
            land_dim_2 = 100,
            land_ownership = T,
            res_birth_type = 2,
            res_death_type = 2,
            lambda = 3,
            remove_pr = 0,
            res_birth_K = 1e+50,
            res_death_K = 2000,
            manage_target = 1000,
            RESOURCE_ini = 1000,
            stakeholders = 8, 
            res_consume = 0.5,
            agent_view = 50,
            times_observe = 10,
            scaring = TRUE, 
            culling = TRUE,
            tend_crops = TRUE, 
            tend_crop_yld = 0.5,
            minimum_cost = 10)
plot_gmse_results(test)
